version: '3.9'
services:
  db:
    image: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: shopdev
      MYSQL_USER: shopdev
      MYSQL_PASSWORD: shopdev1234
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data: