version: '3.9'
services:
  db:
    image: mysql
    container_name: shopdev_db
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: shopdev
      MYSQL_USER: shopdev
      MYSQL_PASSWORD: shopdev1234
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:7.0
    container_name: shopdev_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: