// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/go-ecommerce-backend-api/internal/controller"
	"github.com/go-ecommerce-backend-api/internal/repository"
	"github.com/go-ecommerce-backend-api/internal/service"
)

// Injectors from wire.go:

func InitializeUserController() (*controller.UserController, error) {
	iUserRepository := repository.NewUserRepository()
	iUserService := service.NewUserService(iUserRepository)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
