server:
  port: 8002
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  logLevel: debug
  fileLogName: "./storages/logs/dev.log"
  MaxSize:    500
  MaxBackups: 3
  MaxAge:     28
  Compress:   true
